---
title: "Week4_GIS_home"
output: html_document
date: "2022-11-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(janitor)
library(countrycode)
```
```{r}
shape1 <- st_read ("E:/CASA0005GIS/GIS122/World_Countries__Generalized_.shp")
```
```{r}
csv <- st_read("E:/CASA0005GIS/GIS122/HDR21-22_Composite_indices_complete_time_series.csv")
```
 
```{r}
csv_cleaned <- csv %>% 

 mutate (iso2 = countrycode(iso3,origin = "iso3c", destination = "iso2c"))
```
```{r}
csv_edited <- csv_cleaned %>% select(iso2,country,gii_2010,gii_2019)
```

```{r}
csv_edited[,c(3:4)] <- as.numeric(unlist(csv_edited[,c(3:4)]))
```
```{r}
csv_edited1 <- mutate (csv_edited,difference = gii_2019 - gii_2010)
```
```{r}
# csv into .shp 
ronghe <- shape1 %>%
  clean_names() %>%
  left_join(.,csv_edited1,by=c("iso" ="iso2"))
```
```{r}
# make map 
library(tmap)
library(tmaptools)
tmap_mode("plot")
```
```{r}
tm_shape(ronghe) + 
tm_polygons("difference", 
        style="pretty",
        palette="Blues",
        midpoint=NA,
        title="GIff",
        alpha = 0.5)
```



